name: em_department_guide
description: Emergency Medicine Department Guide

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_launcher: ^5.1.4
  flutter_markdown: ^0.2.0
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
